### ISSUE TITLE
Blynk Setup

### ISSUE THREAD

**Issue by Andycart** [florianL21/LED-ClockShelf#13] opened 2022-01-24 08:27 UTC
Hi

I've tried to use your QR code for the simple Blynk app but Blynk gives me an "invalid token message". Can you help?

**Comment by Cayn183** [comment] 2022-01-24 13:58
Hey, 
I had the Same problem, you have to use the old blynk application it is called blynk only and has a big green B in the icon.
I Hope i helped you.

**Comment by Andycart** [comment] 2022-01-24 15:07
Many thanks. I'll try it. That also probably explains why my auth token
keeps getting rejected. The new Blynk probably needs the template and device
names sending with it

**Comment by imCharlieB** [comment] 2022-06-01 16:43
Cant create account with the old blynk app just got done trying anyway to make this work with the new blynk?

**Comment by florianL21** [comment] 2022-06-02 15:51
I will look into it probably this weekend and update this issue if I manage to make it work

**Comment by florianL21** [comment] 2022-06-17 18:25
I've had time today to look into it. Can some of you try it out before I merge it back to master? I have tested it on my clock, and it seems to work well enough without having the paid subscription:
https://github.com/florianL21/LED-ClockShelf/tree/blynk-update
I've committed the Blynk Template ID as well because I could not find any other way to share this, I hope that it is in fact intended to be used that way :p

**Comment by camman61898** [comment] 2022-07-08 14:59
Hey, this project is awesome! I am about to start on it, did you ever confirm that the updates in the blynk-update did work? Also, it is possible to run this project without any Blynk program, right? But it will still connect to the internet to get the proper time and account for daylight savings?

**Comment by florianL21** [comment] 2022-07-08 15:08
Thanks :)
I confirmed it on my own clock and the blynk updates do seem to be working without any issues so far for me.
Yes it's also possible to run it without blynk and it will still fetch the time from the internet.
Running without blynk will however disable some functionality like the alarms and timers but if you don't plan on using them and you are happy to choose the color for your LEDs once and then leave it the same there is nothing preventing you to get rid of blynk ;)
All the blynk features that I am using are supported in the free version of the service since I am not a big fan of subscriptions myself.

Daylight savings should be accounted for just make sure to change the timezone string to the correct one for your location. There is a comment in the code linking to to the website I used to set mine.

**Comment by camman61898** [comment] 2022-07-08 15:17
Okay awesome, so how do I go about setting up the device with my Blynk account? Do you have a preset config that I could use to follow? I tried to set up Blynk with a previous project and I could not get it to work at all, so I am a little tainted from Blynk, but the other project was based on the old Blynk and I was trying to use it with the new Blynk IOT and there was just no way I was going to be able to figure it out since I am a mechanical engineer and not very knowledgeable with software.

**Comment by florianL21** [comment] 2022-07-08 15:32
I did commit my template ID hoping that other people will be able to use it get the same interface in blynk immediately. So in theory, as long as you have your own blynk token for the new blynk iot app all you should need to do is to put that into the correct #define... Hopefully.

I'm not 100% sure because I could not find any documentation on whether blynk intends to share this template ID or not.

All the blynk changes are still on a separate branch btw, so if you want to get to them you would need to download that one. If I can find some time this weekend I will merge it back to master and update the documentation for the new blynk setup. If you can you may want to wait for that so it can be a little easier for you to get things up and running

**Comment by camman61898** [comment] 2022-07-08 15:38
Yeah that would be awesome if you could do that! I will probably give it a shot and see if I can get it to work with the blynk-update branch. I bet I will most likely just disable Blynk because it can get confusing pretty quick, but I will see if I can get it to work! I really appreciate your help.

**Comment by florianL21** [comment] 2022-07-10 15:00
I just merged the Blynk update back to master. The documentation was also updated. 
I did do some testing and could sadly not find any way how I would be able to share the Blynk configuration with anyone currently. So I wrote some instructions on how to replicate my setup manually...

**Comment by themaluxis** [comment] 2022-08-21 17:25
Hi @florianL21 I'm trying to copy your Blynk configuration, but 'im unable to select a string value for the ZeRGBa module. Are you using Blynk on iOS ? Maybe a mobile problem :(

**Comment by florianL21** [comment] 2022-08-21 17:30
Yes might be. I am using Android. What values are you able to select for that widget?

**Comment by themaluxis** [comment] 2022-09-17 13:28
![IMG_3689](https://user-images.githubusercontent.com/2593413/190859399-3b8e15f8-02f3-4e83-a1c3-5e8b7d29efc4.PNG)

Here is what I can see.
So i used an android emulator to do my Blynk dashboard, but I can only change hour colors
If i press ON on other toggle than Hour, everything shutdown, only hour is displayed //

**Comment by florianL21** [comment] 2022-10-04 18:26
It looks like you did not choose the advanced mode for the setting for that widget. Only in advanced mode you can select a string as an input I think:
![IMG_20221004_202609.png](https://user-images.githubusercontent.com/6053565/193896700-fe214d98-75ed-4e14-ab5a-17fa21592f09.png)

**Comment by florianL21** [comment] 2022-10-04 18:29
And for the Hour/minute selector buttons you have to make sure that they are configured to toggle instead of push which is the default. If you then have those mapped to the correct virtual pins, (V14-V17) everything should work as expected

**Comment by J-GitHub1** [comment] 2022-12-15 16:52
@florianL21 absolutely fantastic project. I can't thank you enough for how well-documented the code is.

@themaluxis Did you get it working on android? I can't figure it out in iOS.

**Comment by florianL21** [comment] 2022-12-15 17:21
@J-GitHub1 Thank you :) 
If you get it working let me know what the issue is and I will happily add it to the documentation for future iOS users to find ;)

**Comment by J-GitHub1** [comment] 2022-12-15 23:09
Yeah, looks like the advanced option is not available in the iOS app. I have an old android phone hanging around, so did it on there. Maybe update the documentation to highlight that? Just to stop Apple fan boys and girls like me chasing their tail for hours 🤦🏼‍♂️. 

Also, while your at it maybe add the definitions for switches v14 to v17? 

Last thing the url for the Blynk server is now blynk.cloud I've used that instead of the ip address and it seems to work. 

I hope you don't mind the suggestions I'm sure there's some git magic I should use to make the changes and ask you to accept
them but I really have no idea what I'm doing. 

Thanks again for the awesome enhancement to an already awesome project. You've saved me hours and hours of work.

**Comment by florianL21** [comment] 2022-12-25 22:08
Good catch, I was not aware that the setting for v14 to v17 were missing. I just added them now to the documentation.
I was also able to get a hold of an iPhone to test the RGB setting on, and I can in fact see the merge setting. Are you not able to use this?
![IMG_0002](https://user-images.githubusercontent.com/6053565/209483081-8da1758c-76da-4d9a-9a2c-49644cfafc5d.PNG)

**Comment by J-GitHub1** [comment] 2022-12-26 10:25
Hi, Thanks for checking and getting back. I have the merge option, but when I go in to select data stream, the pin needed is missing. ![image](https://user-images.githubusercontent.com/104653841/209537890-5e401494-fe3c-4956-84b7-a2d32f98e0ec.png)

I don't think it's a problem with your documentation which continues to be awesome. I think it's an issue with blynk. 

Thanks again for this brilliant project.

**Comment by florianL21** [comment] 2022-12-27 10:25
Now I see what you mean. Could you try to set the datastreams for all the colors to the Integer type? I think that might just work without any changes to the code on the clock itself ;)

If it does I will add that to the documentation and then it should also work on iOS

**Comment by J-GitHub1** [comment] 2022-12-27 13:44
Hi,

It didn't work, but I've found a workaround. I changed the V2 data stream type to integer (on the web dashboard) and clicked save/ apply, which allowed me to select V2 in the iOS app for the data stream for the colour picker. After returning to the main page of the app (closing the configuration page), I changed the V2 data stream type back string (on the web dashboard) and clicked save apply. Works lovely now.

Important note, this has to be done last, as any changes to the iOS app cause the work around to break. 

This is not an issue with your implementation but is something blynk need to sort out.

Again massive thank you for the project, your speedy replies and your patience.

**Comment by florianL21** [comment] 2022-12-31 16:06
Thanks for that workaround suggestion! I've added it to the documentation, so hopefully iOS users will now be able to get it up and running without any frustration.

I'm going to close this issue then, since it is now hopefully finally resolved. 

And thanks again @J-GitHub1 for your help with figuring out the issues on iOS :)

**Closed as completed by florianL21** 2022-12-31 16:06 UTC
Labels: enhancement
